services:
    web:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - .:/app
        links:
            - db

    db:
        image: "postgres:9.6"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: hunter2

    redis:
      image: redis:alpine

    celery:
        restart: always
        build: .
        command: celery --A courses.tasks worker -l info
        volumes:
            - .:/app
        environment:
            - DB_HOST=db
            - DB_NAME=web
            - DB_USER=postgres
            - DB_PASS=hunter2
        depends_on:
            - web
            - redis
            - db

    celery-beat:
        build: .
        command: celery --A courses.tasks beat -l info
        volumes:
            - .:/app
        environment:
            - DB_HOST=db
            - DB_NAME=web
            - DB_USER=postgres
            - DB_PASS=hunter2
        depends_on:
            - db
            - redis